#!/bin/bash
#
# Running this script will start an instance of the container, if one is not 
# already running, and then execute the command in the instance.
#
# Cleaning up unwanted instances afterwards is outside the scope of this script.
set -euo pipefail

DOCKER_PREFIX=${DOCKER_PREFIX:-docker.io/wsinpg}
DOCKER_IMAGE=${DOCKER_IMAGE:?required, but was not set}
TAG=${TAG:-latest}

# Colons and slashes are not allowed in Singularity instance names
instance="$DOCKER_IMAGE--$TAG"

if ! singularity instance list | grep "$instance" 2>&1 >/dev/null ; then
    singularity instance start \
        "docker://$DOCKER_PREFIX/$DOCKER_IMAGE:$TAG" "$instance" 2>&1 >/dev/null
fi

singularity exec "instance://$instance" "$@"
