ARG BASE_IMAGE=16.04-base
FROM $BASE_IMAGE

# This default is the latest usable version
ARG IRODS_VERSION="4.2.7"

ARG ENG_BUILD_URL

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/docker/irods

COPY ./scripts/*.sh ./scripts/
COPY ./config/* ./config/
COPY ./patches/* ./patches/

RUN apt-get update && \
    apt-get install -q -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    lsb-release \
    jq \
    netcat \
    patch \
    postgresql \
    rsyslog \
    unattended-upgrades \
    locales && \
    locale-gen en_GB en_GB.UTF-8 && \
    localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8

ENV LANG=en_GB.UTF-8 \
    LANGUAGE=en_GB \
    LC_ALL=en_GB.UTF-8 \
    TZ=/Etc/UTC

# Required to get the externals packages
RUN curl -sSL https://packages.irods.org/irods-signing-key.asc | apt-key add - && \
    echo "deb [arch=amd64] https://packages.irods.org/apt $(lsb_release -sc) main" | \
    tee /etc/apt/sources.list.d/renci-irods.list && \
    apt-get update

RUN test -n "$ENG_BUILD_URL" || \
    { echo "ENG_BUILD_URL build argument is required" >&2; exit 1; }

RUN curl -fsSL -o sanger_engineering_build-irods_4.2.7.tar.gz "$ENG_BUILD_URL" && \
    tar xvf sanger_engineering_build-irods_4.2.7.tar.gz && \
    md5sum sanger_engineering_build_4.2.7/*.deb

RUN apt-get update && apt-get install -y ./sanger_engineering_build_4.2.7/*.deb

RUN /opt/docker/irods/scripts/create_database.sh && \
    /opt/docker/irods/scripts/configure_irods.sh && \
    /opt/docker/irods/scripts/advance_r_object_id.sh

EXPOSE 1247

HEALTHCHECK --interval=10s --timeout=30s --start-period=5s --retries=3 CMD [ "nc", "-v", "-z", "localhost", "1247" ]

ENTRYPOINT []
CMD ["/opt/docker/irods/scripts/start_irods.sh"]
