# This installs Conda with the dependencies of iRODS 4.2.5 in order to
# build iRODS 4.2.5 with Conda.
FROM wsinpg/ub-12.04-conda:latest

COPY ./ubuntu/12.04/pkg /opt/docker/conda/pkg

RUN apt-get update && \
    apt-get install -q -y --no-install-recommends \
    autoconf2.13 \
    binutils \
    help2man \
    libbz2-dev \
    libcurl4-gnutls-dev \
    libpam0g-dev \
    libssl-dev \
    libtool \
    libxml2-dev \
    lsb-release \
    make \
    pkg-config \
    python-software-properties \
    texinfo \
    unixodbc-dev \
    uuid-dev  \
    zlib1g-dev && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends \
    g++-4.8 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50 && \
    dpkg -i /opt/docker/conda/pkg/*.deb && \
    rm -rf /opt/docker/conda/pkg

ENTRYPOINT ["/opt/docker/conda/scripts/docker-entrypoint.sh"]

CMD ["/bin/bash"]
